//! Minimal TypeScript codegen, "kickoff" scope (PLAN.md §9): typed
//! world/interface API surface + embedded digest constant. Deliberately NOT
//! an ergonomic boundary layer — function signatures use the *current
//! interpreter* host-value shapes (contracts/descriptor-ir.md v0.1 note:
//! variant/enum/option/result as single-key `{ [label]: payload }` objects,
//! not the "target" tagged-union shape), because that's what
//! `runtime/src/exec` actually hands back today. Convergence to the target
//! shapes in descriptor-ir.md is explicitly deferred to the bindgen/
//! descriptor-ir convergence milestone; changing this file's output then is
//! expected and fine.
//!
//! Built on `wit_bindgen_core::Source`/`Files` for text accumulation and
//! output collection (the "built on wit-bindgen-core" requirement) — this
//! is a hand-written generator, not a `WorldGenerator` trait implementation;
//! writing a full trait-based generator is future scope once the descriptor
//! IR/bindgen ergonomic convergence lands (CONTRACT: PLAN.md §9 doesn't
//! mandate the trait specifically, only "built on wit-bindgen-core").

use std::fmt::Write as _;

use anyhow::{bail, Context, Result};
use wit_bindgen_core::Source;
use wit_parser::{
    Function, FunctionKind, Handle, Resolve, Type, TypeDefKind, TypeId, WorldId, WorldItem,
    WorldKey,
};

use crate::digest;

pub fn generate(resolve: &Resolve, world: WorldId, expected_digest: &str) -> Result<String> {
    let w = &resolve.worlds[world];
    let mut src = Source::default();

    writeln!(src, "// GENERATED by crates/bindgen — do not edit by hand.")?;
    writeln!(src, "// Source world: {}", w.name)?;
    writeln!(
        src,
        "// Regenerate: cargo run -p bindgen -- <wit-path> --world {} --out <file>",
        w.name
    )?;
    writeln!(src)?;
    writeln!(
        src,
        "import type {{ ComponentHandle }} from \"../../../src/exec/mod.ts\";"
    )?;
    writeln!(
        src,
        "import type {{ WirePlan }} from \"../../../src/plan/mod.ts\";"
    )?;
    writeln!(
        src,
        "import {{ verifyWorldDigest, type DigestMismatch }} from \"../../../src/digest/mod.ts\";\n"
    )?;

    writeln!(src, "/** Canonical structural digest (PLAN.md §9). */")?;
    writeln!(src, "export const WORLD_DIGEST = {expected_digest:?};\n")?;

    writeln!(
        src,
        "/** Verify a loaded plan against this world's expected digest before\n\
         * trusting the typed facade below. Call at instantiate time, before\n\
         * (or instead of) `instantiateComponent` if the plan is untrusted. */\n\
         export function verify(plan: WirePlan): Promise<DigestMismatch | null> {{\n\
         \x20 return verifyWorldDigest(plan, WORLD_DIGEST);\n\
         }}\n"
    )?;

    // Emit named type declarations for every record/variant/enum/flags type
    // reachable from the world's functions (imports + exports), plus
    // resource interfaces. Types declared directly in the world block
    // (hello/values style) live in `resolve.worlds[world]`'s anonymous
    // interface namespace and are not separately named at the WIT level in
    // a way wit_parser exposes as a distinct interface — so we walk
    // function signatures and collect named TypeIds as we go, emitting each
    // exactly once (by TypeId) in first-encountered order.
    let mut emitted = std::collections::BTreeSet::new();
    let mut type_decls = Source::default();

    for (key, item) in w.imports.iter().chain(w.exports.iter()) {
        collect_and_emit_types(resolve, key, item, &mut emitted, &mut type_decls)?;
    }
    src.push_str(&type_decls);

    let mut import_decls = Source::default();
    let mut export_decls = Source::default();
    for (key, item) in &w.imports {
        emit_world_item(resolve, key, item, &mut import_decls)?;
    }
    for (key, item) in &w.exports {
        emit_world_item(resolve, key, item, &mut export_decls)?;
    }

    if !import_decls.as_str().is_empty() {
        writeln!(src, "export interface {}Imports {{", ts_ident(&w.name))?;
        src.push_str(import_decls.as_str());
        writeln!(src, "}}\n")?;
    }
    writeln!(src, "export interface {}Exports {{", ts_ident(&w.name))?;
    src.push_str(export_decls.as_str());
    writeln!(src, "}}\n")?;

    writeln!(
        src,
        "/** Thin typed cast over the runtime's plain instance exports — no\n\
         * ergonomic boundary layer (PLAN.md §9 kickoff scope). */\n\
         export function bind(instance: ComponentHandle): {}Exports {{\n\
         \x20 return instance.exports as unknown as {}Exports;\n\
         }}",
        ts_ident(&w.name),
        ts_ident(&w.name)
    )?;

    Ok(src.as_str().to_string())
}

fn ts_ident(name: &str) -> String {
    // kebab-case -> PascalCase.
    name.split(['-', '_'])
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn ts_field_name(name: &str) -> String {
    // kebab-case -> camelCase, but keep it honest/reversible: WIT kebab
    // names are also valid (quoted) TS property names, so we just quote
    // them verbatim instead of guessing a camelCase mapping that would
    // need an un-mapping step at the runtime boundary. Simpler, and exact.
    format!("{name:?}")
}

fn emit_world_item(
    resolve: &Resolve,
    key: &WorldKey,
    item: &WorldItem,
    out: &mut Source,
) -> Result<()> {
    match item {
        WorldItem::Function(f) => {
            let name = match key {
                WorldKey::Name(n) => n.clone(),
                WorldKey::Interface(_) => bail!("function with interface key"),
            };
            writeln!(out, "  {}: {};", ts_field_name(&name), ts_func_type(resolve, f, None)?)?;
        }
        WorldItem::Interface { id, .. } => {
            let iface = &resolve.interfaces[*id];
            // The runtime keys nested export objects by the *component
            // export name* (`WireExport.name`), which for an interface
            // export is its full qualified name (e.g.
            // "component-engine:resources/counters"), not the bare
            // interface name — verified against
            // `runtime/src/exec/executor.ts`'s `buildExport`/`finish`
            // (`exports[exp.name] = built`, and `exp.name` for a
            // `WireExport::Instance` is the qualified string emitted by
            // translator-shim). Must match `digest::qualified_interface_name`
            // exactly, since that's also what the digest identifies this
            // item by.
            let name = crate::digest::qualified_interface_name(resolve, *id)?;
            writeln!(out, "  {:?}: {{", name)?;
            for (fname, f) in &iface.functions {
                let resource = method_resource(f);
                writeln!(
                    out,
                    "    {}: {};",
                    ts_field_name(fname),
                    ts_func_type(resolve, f, resource)?
                )?;
            }
            writeln!(out, "  }};")?;
        }
        WorldItem::Type { .. } => {
            // Named world-level type export; not itself a callable/instance
            // member, already emitted as a type declaration.
        }
    }
    Ok(())
}

fn method_resource(f: &Function) -> Option<TypeId> {
    match f.kind {
        FunctionKind::Method(id)
        | FunctionKind::AsyncMethod(id)
        | FunctionKind::Static(id)
        | FunctionKind::AsyncStatic(id)
        | FunctionKind::Constructor(id) => Some(id),
        FunctionKind::Freestanding | FunctionKind::AsyncFreestanding => None,
    }
}

fn ts_func_type(resolve: &Resolve, f: &Function, resource: Option<TypeId>) -> Result<String> {
    let _ = resource; // see digest.rs canon_func: f.params already has `self`.
    let mut params = Vec::new();
    for p in &f.params {
        params.push(format!(
            "{}: {}",
            ts_param_name(&p.name),
            ts_value_type(resolve, p.ty)?
        ));
    }
    let ret = match (f.result, &f.kind) {
        (Some(t), _) => ts_value_type(resolve, t)?,
        (None, FunctionKind::Constructor(rid)) => resource_ts_name(resolve, *rid)?,
        (None, _) => "void".to_string(),
    };
    Ok(format!("({}) => {ret}", params.join(", ")))

}

fn ts_param_name(name: &str) -> String {
    // Same reasoning as ts_field_name: quote to stay exact, but parameter
    // position syntax needs a bare identifier, so map kebab-case to
    // camelCase here (this is purely a *display* name in the .d.ts function
    // type — TS call sites are positional, so this mapping cannot cause a
    // wire mismatch either direction).
    let mut out = String::new();
    let mut upper_next = false;
    for c in name.chars() {
        if c == '-' {
            upper_next = true;
            continue;
        }
        if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() || out.chars().next().unwrap().is_ascii_digit() {
        out = format!("_{out}");
    }
    out
}

fn resource_ts_name(resolve: &Resolve, id: TypeId) -> Result<String> {
    let name = resolve.types[id]
        .name
        .as_deref()
        .context("resource type has no name")?;
    Ok(ts_ident(name))
}

/// Host-value type mapping (descriptor-ir.md type-mapping table; value
/// *shapes* per the v0.1 interpreter-truth note — see module docs).
fn ts_value_type(resolve: &Resolve, ty: Type) -> Result<String> {
    Ok(match ty {
        Type::Bool => "boolean".to_string(),
        Type::U8 | Type::U16 | Type::U32 | Type::S8 | Type::S16 | Type::S32 | Type::F32
        | Type::F64 => "number".to_string(),
        Type::U64 | Type::S64 => "bigint".to_string(),
        Type::Char => "string".to_string(),
        Type::String => "string".to_string(),
        Type::ErrorContext => "unknown /* error-context: M2 */".to_string(),
        Type::Id(id) => ts_typedef_value_type(resolve, id)?,
    })
}

fn ts_typedef_value_type(resolve: &Resolve, id: TypeId) -> Result<String> {
    let def = &resolve.types[id];
    Ok(match &def.kind {
        TypeDefKind::Type(t) => ts_value_type(resolve, *t)?,
        TypeDefKind::Record(_) | TypeDefKind::Variant(_) | TypeDefKind::Enum(_)
        | TypeDefKind::Flags(_) => {
            // Named types were pre-emitted as declarations; reference by name.
            def.name
                .as_ref()
                .map(|n| ts_ident(n))
                .context("anonymous record/variant/enum/flags type")?
        }
        TypeDefKind::Tuple(t) => {
            // Current interpreter truth (cabi/types.ts `despecialize`):
            // tuple<T,U,...> is despecialized to a record `{ "0": T, "1": U,
            // ... }` before lift/lower — NOT a TS tuple/array. This is the
            // *v0.1 implementation* shape (descriptor-ir.md's table target
            // shape, an actual array, is future work post-convergence).
            let fields: Result<Vec<String>> = t
                .types
                .iter()
                .enumerate()
                .map(|(i, e)| Ok(format!("{i:?}: {}", ts_value_type(resolve, *e)?)))
                .collect();
            format!("{{ {} }}", fields?.join("; "))
        }
        TypeDefKind::List(el) => {
            if matches!(el, Type::U8) {
                "Uint8Array".to_string()
            } else {
                format!("Array<{}>", ts_value_type(resolve, *el)?)
            }
        }
        TypeDefKind::FixedLengthList(el, _) => format!("Array<{}>", ts_value_type(resolve, *el)?),
        TypeDefKind::Map(k, v) => format!(
            "Array<[{}, {}]>",
            ts_value_type(resolve, *k)?,
            ts_value_type(resolve, *v)?
        ),
        // option<T> CURRENT interpreter shape (cabi/lift.ts
        // `liftFlatVariant`: option despecializes to variant{none,some} and
        // the interpreter's variant lift always returns a single-key
        // object `{ [label]: payload }` — there is no `undefined`-based
        // shortcut in the running code today, contrary to
        // descriptor-ir.md's *target* table, which is explicitly a v0.1
        // "destination, not current truth" per that doc's status note).
        TypeDefKind::Option(t) => {
            format!("({{ none: null }} | {{ some: {} }})", ts_value_type(resolve, *t)?)
        }
        // result<T,E> host shape: `{ ok: T } | { error: E }` — note the
        // wire/in-memory name split (descriptor-ir.md v0.1 amendment #1:
        // wire `err` vs runtime `error`); bindgen faces the runtime, so
        // `error` is what call sites actually see.
        TypeDefKind::Result(r) => {
            let ok = match r.ok {
                Some(t) => ts_value_type(resolve, t)?,
                None => "null".to_string(),
            };
            let err = match r.err {
                Some(t) => ts_value_type(resolve, t)?,
                None => "null".to_string(),
            };
            format!("({{ ok: {ok} }} | {{ error: {err} }})")
        }
        TypeDefKind::Handle(Handle::Own(rid)) | TypeDefKind::Handle(Handle::Borrow(rid)) => {
            resource_ts_name(resolve, *rid)?
        }
        TypeDefKind::Future(_) | TypeDefKind::Stream(_) => {
            "unknown /* async: M2 */".to_string()
        }
        TypeDefKind::Resource => bail!("bare resource used as a value type"),
        TypeDefKind::Unknown => bail!("unresolved type in a resolved Resolve"),
    })
}

/// Pre-pass: emit `interface`/`type` declarations for every named
/// record/variant/enum/flags type and a resource-handle interface for every
/// named resource, each exactly once, walking function signatures reachable
/// from world imports/exports.
fn collect_and_emit_types(
    resolve: &Resolve,
    _key: &WorldKey,
    item: &WorldItem,
    emitted: &mut std::collections::BTreeSet<TypeId>,
    out: &mut Source,
) -> Result<()> {
    match item {
        WorldItem::Function(f) => walk_func_types(resolve, f, emitted, out)?,
        WorldItem::Interface { id, .. } => {
            let iface = &resolve.interfaces[*id];
            for tid in iface.types.values() {
                emit_named_type(resolve, *tid, emitted, out)?;
            }
            for f in iface.functions.values() {
                walk_func_types(resolve, f, emitted, out)?;
            }
        }
        WorldItem::Type { id: tid, .. } => emit_named_type(resolve, *tid, emitted, out)?,
    }
    Ok(())
}

fn walk_func_types(
    resolve: &Resolve,
    f: &Function,
    emitted: &mut std::collections::BTreeSet<TypeId>,
    out: &mut Source,
) -> Result<()> {
    for p in &f.params {
        walk_type(resolve, p.ty, emitted, out)?;
    }
    if let Some(t) = f.result {
        walk_type(resolve, t, emitted, out)?;
    }
    Ok(())
}

fn walk_type(
    resolve: &Resolve,
    ty: Type,
    emitted: &mut std::collections::BTreeSet<TypeId>,
    out: &mut Source,
) -> Result<()> {
    if let Type::Id(id) = ty {
        // Recurse into structural children first (dependency-before-use).
        match &resolve.types[id].kind {
            TypeDefKind::Type(t) => walk_type(resolve, *t, emitted, out)?,
            TypeDefKind::Record(r) => {
                for f in &r.fields {
                    walk_type(resolve, f.ty, emitted, out)?;
                }
            }
            TypeDefKind::Tuple(t) => {
                for t in &t.types {
                    walk_type(resolve, *t, emitted, out)?;
                }
            }
            TypeDefKind::Variant(v) => {
                for c in &v.cases {
                    if let Some(t) = c.ty {
                        walk_type(resolve, t, emitted, out)?;
                    }
                }
            }
            TypeDefKind::Option(t) => walk_type(resolve, *t, emitted, out)?,
            TypeDefKind::Result(r) => {
                if let Some(t) = r.ok {
                    walk_type(resolve, t, emitted, out)?;
                }
                if let Some(t) = r.err {
                    walk_type(resolve, t, emitted, out)?;
                }
            }
            TypeDefKind::List(t) | TypeDefKind::FixedLengthList(t, _) => {
                walk_type(resolve, *t, emitted, out)?
            }
            TypeDefKind::Map(k, v) => {
                walk_type(resolve, *k, emitted, out)?;
                walk_type(resolve, *v, emitted, out)?;
            }
            _ => {}
        }
        emit_named_type(resolve, id, emitted, out)?;
    }
    Ok(())
}

fn emit_named_type(
    resolve: &Resolve,
    id: TypeId,
    emitted: &mut std::collections::BTreeSet<TypeId>,
    out: &mut Source,
) -> Result<()> {
    if emitted.contains(&id) {
        return Ok(());
    }
    let def = &resolve.types[id];
    match &def.kind {
        TypeDefKind::Record(r) => {
            let Some(name) = &def.name else { return Ok(()) };
            emitted.insert(id);
            writeln!(out, "export interface {} {{", ts_ident(name))?;
            for f in &r.fields {
                writeln!(
                    out,
                    "  {}: {};",
                    ts_field_name(&f.name),
                    ts_value_type(resolve, f.ty)?
                )?;
            }
            writeln!(out, "}}\n")?;
        }
        TypeDefKind::Variant(v) => {
            let Some(name) = &def.name else { return Ok(()) };
            emitted.insert(id);
            // Interpreter host shape (descriptor-ir.md table / cabi/types.ts
            // docstring): single-key object `{ [caseLabel]: payload|null }`.
            let arms: Result<Vec<String>> = v
                .cases
                .iter()
                .map(|c| {
                    Ok(format!(
                        "{{ {}: {} }}",
                        ts_field_name(&c.name),
                        match c.ty {
                            Some(t) => ts_value_type(resolve, t)?,
                            None => "null".to_string(),
                        }
                    ))
                })
                .collect();
            writeln!(
                out,
                "export type {} =\n  | {};\n",
                ts_ident(name),
                arms?.join("\n  | ")
            )?;
        }
        TypeDefKind::Enum(e) => {
            let Some(name) = &def.name else { return Ok(()) };
            emitted.insert(id);
            // Current interpreter shape (cabi/types.ts `despecialize`: enum
            // -> variant with null-payload cases; lift.ts's
            // `liftFlatVariant` always returns `{ [label]: payload }`) —
            // single-key objects, not bare label strings.
            let arms: Vec<String> = e
                .cases
                .iter()
                .map(|c| format!("{{ {}: null }}", ts_field_name(&c.name)))
                .collect();
            writeln!(out, "export type {} =\n  | {};\n", ts_ident(name), arms.join("\n  | "))?;
        }
        TypeDefKind::Flags(fl) => {
            let Some(name) = &def.name else { return Ok(()) };
            emitted.insert(id);
            writeln!(out, "export interface {} {{", ts_ident(name))?;
            for f in &fl.flags {
                writeln!(out, "  {}: boolean;", ts_field_name(&f.name))?;
            }
            writeln!(out, "}}\n")?;
        }
        TypeDefKind::Resource => {
            let Some(name) = &def.name else { return Ok(()) };
            emitted.insert(id);
            // Handle-shaped interface only (descriptor-ir.md: "own/borrow ->
            // runtime handle class"); the v1 interpreter hands back a plain
            // handle number at this layer (see cabi/types.ts docstring) —
            // resource *classes* are ergonomic-layer future work, so this
            // is deliberately just a nominal branded marker type for now.
            writeln!(
                out,
                "export type {} = number & {{ readonly __resource: {:?} }};\n",
                ts_ident(name),
                name
            )?;
        }
        _ => {}
    }
    Ok(())
}

/// Convenience used by the CLI: compute the digest and generate in one
/// step, returning `(canonical_json, digest, generated_ts)`.
pub fn generate_with_digest(
    resolve: &Resolve,
    world: WorldId,
) -> Result<(String, String, String)> {
    let d = digest::compute(resolve, world)?;
    let ts = generate(resolve, world, &d.digest)?;
    Ok((d.canonical_json, d.digest, ts))
}
